// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKZhaJXRG2UR23ngIn3RCuvSZELe2CYvE',
    appId: '1:845636228906:web:b886040d86bcfb41767053',
    messagingSenderId: '845636228906',
    projectId: 'uts-app-healthmate-islami',
    authDomain: 'uts-app-healthmate-islami.firebaseapp.com',
    storageBucket: 'uts-app-healthmate-islami.firebasestorage.app',
    measurementId: 'G-47T1N4T579',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTs9M4hIiwOD_ljJEnXw2EzuzTFxNyG8E',
    appId: '1:845636228906:android:5dd682b602ba5191767053',
    messagingSenderId: '845636228906',
    projectId: 'uts-app-healthmate-islami',
    storageBucket: 'uts-app-healthmate-islami.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVGYUvGKM5WVslMYjziAYv2DwoEcWMut4',
    appId: '1:845636228906:ios:bfb896cdd62ca793767053',
    messagingSenderId: '845636228906',
    projectId: 'uts-app-healthmate-islami',
    storageBucket: 'uts-app-healthmate-islami.firebasestorage.app',
    iosBundleId: 'com.example.utsAppHealthmateIslami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVGYUvGKM5WVslMYjziAYv2DwoEcWMut4',
    appId: '1:845636228906:ios:bfb896cdd62ca793767053',
    messagingSenderId: '845636228906',
    projectId: 'uts-app-healthmate-islami',
    storageBucket: 'uts-app-healthmate-islami.firebasestorage.app',
    iosBundleId: 'com.example.utsAppHealthmateIslami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKZhaJXRG2UR23ngIn3RCuvSZELe2CYvE',
    appId: '1:845636228906:web:92bc5095a82bce69767053',
    messagingSenderId: '845636228906',
    projectId: 'uts-app-healthmate-islami',
    authDomain: 'uts-app-healthmate-islami.firebaseapp.com',
    storageBucket: 'uts-app-healthmate-islami.firebasestorage.app',
    measurementId: 'G-PM2P5SVHKY',
  );
}
